CREATE TABLE funding_settlements (
    id UUID NOT NULL PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL UNIQUE,
    fixing_price DOUBLE PRECISION NOT NULL,
    funding_rate DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
